In [1]:
import numpy as np

creating arrays 1d and 2d

In [2]:
# 1D array
arr1 = np.array([10, 20, 30, 40])
print(arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


array properties<br>
shape (rows and columns), number of dimensions, total elements, and data type

In [3]:
print(arr2.shape)   # rows, columns
print(arr2.ndim)    # dimensions
print(arr2.size)    # total elements
print(arr2.dtype)   # data type

(2, 3)
2
6
int64


array indexing

In [4]:
print(arr1[0])      # first element
print(arr2[1][2])   # row 1, col 2

10
6


array slicing <br>
Slicing allows us to extract a portion of an array using a range of indices


In [5]:
print(arr1[1:3])
print(arr2[:, 1])   # second column

[20 30]
[2 5]


mathematical operations on array

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("addition : ",a + b)
print("subtraction : ",a - b)
print("multiplication : ",a * b)
print("division : ",a / b)

addition :  [5 7 9]
subtraction :  [-3 -3 -3]
multiplication :  [ 4 10 18]
division :  [0.25 0.4  0.5 ]


scalar operations 

In [21]:
print('original arry a: ',a)
print('original arry b: ',b)
print("adding scalar 10 a: ",a + 10)
print('multiplying scalar 2 b: ',a * 2)

original arry a:  [1 2 3]
original arry b:  [4 5 6]
adding scalar 10 a:  [11 12 13]
multiplying scalar 2 b:  [2 4 6]


array functions <br>
built-in functions like sum, mean, max, min, and standard deviation

In [13]:
arr = np.array([10, 5, 8, 20, 3])

print('sum :',np.sum(arr))
print('mean :',np.mean(arr))
print('maximum :',np.max(arr))
print('minimun :',np.min(arr))
print('standare deviation :',np.std(arr))

sum : 46
mean : 9.2
maximum : 20
minimun : 3
standare deviation : 5.912698199637793


reshaping arrays

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("array before reshaping:",arr)
reshaped = arr.reshape(2, 3) #convert arrays into 2 rows and 3colunms
print("new reshaped array:",reshaped)

array before reshaping: [1 2 3 4 5 6]
new reshaped array: [[1 2 3]
 [4 5 6]]


random arrays<br>
random arras are generated using np.random.randint(low, high=None, size=None, dtype=int)

In [ ]:
random_arr = np.random.randint(1, 100, size=10) # 1 to 100 ,100 excluded
print("random array : ",random_arr)

random array :  [93 97 59  5 28 82 61 86 24 91]


filtering array

In [18]:
arr = np.array([10, 25, 30, 45, 50])
print("the array: ",arr)
print('elements greater than 30:',arr[arr > 30])

the array:  [10 25 30 45 50]
elements greater than 30: [45 50]
